### ISSUE TITLE
Rendering empty text blocks

### ISSUE THREAD

**Issue by sprmn** [globocom/react-native-draftjs-render#16]
It appears empty text blocks (for instance due to line breaks) are not rendered. Am I correct?

I would happily submit a PR if there is no solution available yet. Is there any solution available?

**Comment by raphaelpor** [comment]
Hi @sprmn!
We'll discuss it and reply soon.

Thanks for your feedback. :)

**Comment by Canedo** [comment]
Hey @sprmn !
We discuss internally and we think that empty blocks should not be rendered by default.

But it would be cool to have a boolean to handle that (with the default value as false), that could make it possible to render empty text blocks. With that we will keep it compatible with us and everybody that uses our project, but in certains scenarios you could just pass this flag as props to DraftJsRender and empty text blocks would be available to any usage.

We would love a PR like that if you are really interested.

Thank you and sorry for us being late to answer you.

**Comment by jayporta** [comment]
Sorry to post in a closed thread, but did anyone ever work on this? I'm also trying to get a double line break to render.
