### ISSUE TITLE
image not visible in Android and empty in ios

### ISSUE THREAD

**Issue by EyreGe** [globocom/react-native-draftjs-render#19]

**Comment by Liqiankun** [comment]
Yes,  I got the same issue!

**Comment by YanfangLi248** [comment]
I got the same issue and the react-native version is 0.47.1

**Comment by Liqiankun** [comment]
@Canedo `"react-native": "^0.45.1"` This is my version.

**Comment by EyreGe** [comment]
@Canedo "react-native": "^0.45.1"

**Comment by raphaelpor** [comment]
Hi folks!
_Images_ aren't present on basic draft.js types, so we don't support it by default.
You need to create a atomic render for images.

See this example: https://github.com/globocom/react-native-draftjs-render/blob/master/sample/src/index.js
