### ISSUE TITLE
blank block on the bottom 

### ISSUE THREAD

**Issue by Liqiankun** [globocom/react-native-draftjs-render#20]
Look at this pic!
![wechatimg9](https://user-images.githubusercontent.com/11532418/28905658-9e00f638-7844-11e7-85d4-be91c3dcecba.jpeg)

**Comment by Liqiankun** [comment]
0.45.1 @Canedo

**Comment by raphaelpor** [comment]
Hi @Liqiankun!

Could you show us your draft.js data?

**Comment by raphaelpor** [comment]
@Liqiankun any update?

**Comment by psyzz** [comment]
@raphaelpor i experience the same behaviour, big blank at the bottom.
Here a screenshot when i'm using your sample:

![screen shot 2017-10-10 at 14 06 09](https://user-images.githubusercontent.com/1016441/31385688-6954e808-adc4-11e7-940f-91c06db9b492.png)

react & rn version:

"react": "16.0.0-alpha.12"
"react-native": "0.47.1"

**Comment by raphaelpor** [comment]
Hi @psyzz!
Thanks for your information.

Which device/simulator are you using?

**Comment by raphaelpor** [comment]
Hi guys!

Any update on it?
