### ISSUE TITLE
support for react 15.5 and higher

### ISSUE THREAD

**Issue by Yoruba** [globocom/react-native-draftjs-render#21]
Please add support for react 15.5 and higher by replacing in index.js

`import React, { PropTypes} from 'react';`

with

`import PropTypes from 'prop-types'`

And use PropTypes directly in DraftJsText.js, UnorderedListItem.js, BlockQuote.js, OrderedListItem.js and TextStyled.js

```
import PropTypes from 'prop-types'

DraftJsText.propTypes = {
  text: PropTypes.string,
  customStyles: PropTypes.any,
  inlineStyles: PropTypes.array,
};
```
Thanks, Adri

**Comment by raphaelpor** [comment]
Hi @Yoruba!
We'll add this support it soon.

Thanks for your contribution.

**Comment by Canedo** [comment]
hey @Yoruba! 
We are going to release a react 15.5 compatible version on the next couple days and another version (probably next week) compatible with react-native 0.47.2 + react 16.0.0-alpha12.

**Comment by raphaelpor** [comment]
Hi @Yoruba!

The first release compatible with React 15.5 is available at [NPM](https://www.npmjs.com/package/react-native-draftjs-render) (e0cd4c1).
