### ISSUE TITLE
Support for (un)ordered-list-item nesting

### ISSUE THREAD

**Issue by Yoruba** [globocom/react-native-draftjs-render#24]
Hello, it would be nice to have support for nested list-items like the screen shot.
See the "depth" property of the "type": "ordered-list-item",
Level one  = "depth": 0
Level two =  "depth": 1

![image](https://user-images.githubusercontent.com/1730709/30648858-4fec9730-9e1f-11e7-8178-6592de9fa01e.png)

```
{
  "entityMap": {},
  "blocks": [
     {
      "key": "1pdm1",
      "text": "Level 1",
      "type": "ordered-list-item",
      "depth": 0,
      "inlineStyleRanges": [],
      "entityRanges": [],
      "data": {}
    },
    {
      "key": "1sd0p",
      "text": "Level 2",
      "type": "ordered-list-item",
      "depth": 1,
      "inlineStyleRanges": [],
      "entityRanges": [],
      "data": {}
    }
  ]
}
```
react-navtive-drafjs-render renders the object like this.
![image](https://user-images.githubusercontent.com/1730709/30649317-3cf6e56c-9e20-11e7-8094-72aa36219e81.png)

Thanks, Adri

**Comment by raphaelpor** [comment]
Hello, @Yoruba!

It's a nice feature, but it isn't at our roadmap for now.
Could you help us with it?

Thanks.

**Comment by Yoruba** [comment]
I will give a try in the coming weeks.
I let you know when it is done.

**Comment by Yoruba** [comment]
This option is implemented
