### ISSUE TITLE
support for textInput field

### ISSUE THREAD

**Issue by Thanmai-C** [globocom/react-native-draftjs-render#27]
I checked your sample and tried it on the emulator, but you are rendering the static data that you get from a json file.
Is there any possibility for having a textInput component and have the text entered dynamically and add the styles/images/links to the entered text?
Please help.

**Comment by rebecabordini** [comment]
The purpose of this project is just render the result provided from an Draft.JS editor. In our case we are using [this](https://github.com/globocom/megadraft) one. Maybe you should look for an DraftJS editor in React Native.

**Comment by Thanmai-C** [comment]
Any idea which library supports that kind?

**Comment by rebecabordini** [comment]
You can look [here](https://github.com/nikgraf/awesome-draft-js) what are the resources for Draft.JS
