### ISSUE TITLE
Any support for text selection?

### ISSUE THREAD

**Issue by Naoto-Ida** [globocom/react-native-draftjs-render#28]
Awesome project btw.

Would it be possible to support granular text selection?

**Comment by raphaelpor** [comment]
Hi @Naoto-Ida!
It would be great! We'll add it to our roadmap, but we accept Pull Requests too.
Thanks for your suggestion.

**Comment by raphaelpor** [comment]
Hello @Naoto-Ida!

Check out this realease: https://github.com/globocom/react-native-draftjs-render/releases/tag/v2.7.0
I think it helps you. 😃
