### ISSUE TITLE
No line break after paragraphs?

### ISSUE THREAD

**Issue by natashache** [globocom/react-native-draftjs-render#32]
I'm trying to render multiple paragraphs. The rendered texts show no breaks between paragraphs, which makes it very hard to read:

![img_4513](https://user-images.githubusercontent.com/19754530/34858856-b503a802-f720-11e7-8f08-4fb1b84dbaf8.jpg)

As a comparison, here's the same text rendered on the web:
![screenshot 2018-01-11 22 40 56](https://user-images.githubusercontent.com/19754530/34858908-0f0138a6-f721-11e7-936f-c2d799e6c9e8.png)

Is it possible to show line breaks? I tried adding marginBottom in paragraph's custom styles, like so:
```
        const customStyles = StyleSheet.flatten({
          paragraph: {
            marginBottom: 7,
            fontSize: 14,
          },
        });
```
It doesn't work. @raphaelpor @Canedo  could you help?

**Comment by Canedo** [comment]
Hello @natashache . 

I'll take a look about that issue in the next couple days. Can you provide us how your data is coming? How the contentState is on your scenario? It'd help a lot!

Thank you for your issue!

**Comment by natashache** [comment]
Hi @Canedo 

The contentState is from our database, which is stored as string.

After fetching the data from the database, I do this:
```
            blocks = getRNDraftJSBlocks({
                contentState: JSON.parse(soundcast.long_description),
                customStyles,
            });
```
where `soundcast.long_description` is the content state string from the database. And then in render function I have:
```
                <View style={[styles.section, { paddingTop: 31 }]}>
                    {
                        blocks
                    }
                </View>
```
Here is an example of `JSON.parse(soundcast.long_description)`. Sorry it's kind of long.
```
{ entityMap: {},
  blocks: 
   [ { key: 'cb1uu',
       text: 'Despite promises of "fast and easy" results from slick marketers, real personal growth is neither fast nor easy. The truth is that hard work, courage, and self-discipline are required to achieve meaningful results--results that are not attained by those who cling to the fantasy of achievement without effort.',
       type: 'unstyled',
       depth: 0,
       inlineStyleRanges: [Object],
       entityRanges: [],
       data: {} },
     { key: 'acahp',
       text: 'Personal Development for Smart People reveals the unvarnished truth about what it takes to consciously grow as a human being. In this course, you\'ll learn practical, insightful methods for improving your health, relationships, career, finances, and more. You\'ll see how to become the conscious creator of your life instead of feeling hopelessly adrift, enjoy a fulfilling career that honors your unique self-expression, wake up early feeling motivated, energized, and enthusiastic, achieve inspiring goals with disciplined daily habits and much more.',
       type: 'unstyled',
       depth: 0,
       inlineStyleRanges: [Object],
       entityRanges: [],
       data: {} },
     { key: '8t85h',
       text: 'With his refreshingly honest yet highly motivating style, Steve Pavlina will help you courageously explore, creatively express, and consciously embrace your extraordinary human journey.',
       type: 'unstyled',
       depth: 0,
       inlineStyleRanges: [Object],
       entityRanges: [],
       data: {} } ] }
```
Here is what it looks like when rendered on the web:
![screenshot 2018-02-18 11 40 21](https://user-images.githubusercontent.com/19754530/36354333-98a38612-14a0-11e8-8ebc-0c642cefd849.png)

And here is what it looks like when rendered on mobile app, using react-native-draftjs-render. As you can see, no space between paragraphs:
![img_4693](https://user-images.githubusercontent.com/19754530/36354340-d6d9bfb4-14a0-11e8-9a43-31d392fb6caa.jpg)

**Comment by natashache** [comment]
@Canedo any update on this?

**Comment by raphaelpor** [comment]
Hello @natashache!

Could you please try this?
```js
const customStyles = StyleSheet.flatten({
  unstyled: {
    marginBottom: 7,
    fontSize: 14,
  },
});
```

It's because the type of the blocks is `unstyled`. So I think you need to use it in your styles.
😉
