### ISSUE TITLE
Can I pass custom props to the atomic Handler ?

### ISSUE THREAD

**Issue by gogoku** [globocom/react-native-draftjs-render#33]
I have an entityMap object need to be passed to atomic handler, currently only the atomic blocks in blocks object is passed

i have attached the screenshot of the object from my DraftJS  

![image](https://user-images.githubusercontent.com/25707104/35288622-3591a550-008b-11e8-9a27-f30751c9e3d6.png)

**Comment by raphaelpor** [comment]
Hi @gogoku!
It's very important for atomic handlers and we need to make a new release to fix it.

Thanks for your feedback! We'll do it as soon as possible.

**Comment by gogoku** [comment]
@raphaelpor Thanks , i have a workaround temporarily for it, Hoping to see the fix soon.

**Comment by raphaelpor** [comment]
Hello @gogoku!

Check out this realease: https://github.com/globocom/react-native-draftjs-render/releases/tag/v2.6.0
I think it helps you. 😃
