### ISSUE TITLE
下载下来的模块没有打包怎么办？

### ISSUE THREAD

**Issue by zhaoleiWeb** [globocom/react-native-draftjs-render#43]
下载下来的模块没有打包怎么办？

**Comment by jayporta** [comment]
@zhaoleiWeb （不好意思，我的中文不太好但是，我会尝试帮助你）你使用NPM吗？你会打英文吗？我不知道是否这个模块程序员会不会看懂中文。

**Comment by Canedo** [comment]
Please repost your issue in english so we can help you properly.
