### ISSUE TITLE
What is DraftJs/contentState?

### ISSUE THREAD

**Issue by adamsythe** [globocom/react-native-draftjs-render#54]
In the getting started it says the only library we need is this one, but then in the example it says to import DraftJs/contentState which doesnt exist?  

Sorry if this is the wrong place to ask

**Comment by chrise86** [comment]
@adamsythe what did you deduce from this?

EDIT: think I get it, docs are very misleading!

**Comment by MaxInMoon** [comment]
Why this issue is closed without resolution?

**Comment by philohelp** [comment]
I got trapped too. I had the impression that I had to install draftJs and then import it.
