### ISSUE TITLE
writingDirection prop is not passed as textProps

### ISSUE THREAD

**Issue by teod** [globocom/react-native-draftjs-render#56]
`writingDirection` prop is not working when pass through `textProps`

```
  getRNDraftJSBlocks({
    contentState,
    textProps: { selectable: true, writingDirection: 'rtl' },
    customStyles,
  })
```

https://facebook.github.io/react-native/docs/text.html#props

**Comment by raphaelpor** [comment]
Hello @teod!

I think `writingDirection` is a `style` property. See: https://facebook.github.io/react-native/docs/text.html#style
Could you try that?

**Comment by teod** [comment]
Yes, you're right, thank you for the help !
