### ISSUE TITLE
Embed content support

### ISSUE THREAD

**Issue by GuillaumeMunsch** [globocom/react-native-draftjs-render#8]
Hi !

First of all, great work on this ! I totally needed a project like yours and I'm happy you did it :)

Then, I'm here to make a "request". I wanted to know if you guys are planning to support the embed content (for youtube videos for example) ?

Thanks in advance :)

**Comment by rebecabordini** [comment]
Hey! 

In DraftJS there are some components with atomic namespace like images, videos, etc. The purpose of react-native-draft-js-render is only render the basic ones, but you can create an atomic handler by yourself. You can see an example in [index.js](https://github.com/globocom/react-native-draftjs-render/blob/master/sample/src/index.js) file.

```
const atomicHandler = (item: Object): any => {
  switch (item.data.type) {
    case 'backstage-photo':
      return (
        <View key={item.key} style={{ flex: 1 }}>
          <Image
            style={{ width: 288, height: 161 }}
            source={{ uri: item.data.file.url }}
          />
        </View>
      );
    default:
      return null;
  }
};
```
