### ISSUE TITLE
Copyright holder and license

### ISSUE THREAD

**Issue by marcelometal** [globocom/react-native-draftjs-render#9]
Hi,
Could you please put the copyright holder and license inside each file? This way there is no chance of someone stumbling across a piece of code without being exposed to the license.

Example for `react-native-draftjs-render` files:

```
/*
 * Copyright (c) 2017, Globo.com (https://github.com/globocom)
 *
 * License: MIT
 */
```

**Comment by Canedo** [comment]
Hey @marcelometal . It's done here https://github.com/globocom/react-native-draftjs-render/commit/52a44352ebdfb4122d28e0c05e93f43294afa6d3 .

Thank you for opening this issue.
